function(add_game_shared_sources target)
	target_sources(${target}
		PRIVATE
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/bitvec.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/voice_common.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/crossbow.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/crowbar.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/egon.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/gauss.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/handgrenade.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/hl_wpn_glock.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/hornetgun.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/mp5.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/python.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/rpg.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/satchel.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/shotgun.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/squeakgrenade.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/tripmine.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/weapons_shared.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/entities/items/weapons/weapons.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_debug.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_debug.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_defs.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_info.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_materials.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_math.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_movevars.h
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_shared.cpp
			${CMAKE_CURRENT_FUNCTION_LIST_DIR}/player_movement/pm_shared.h)
endfunction()
